### ISSUE TITLE
Less satisfying results on the MipNerf-360 dataset

### ISSUE THREAD

**Issue by hyzhou404** [fudan-zvg/gaussian-raytracing#4]
Thanks for your wonderful implementation!

The method performs pretty well on the Nerf-synthetic dataset.
However, I notice that the results are less satisfying on the MipNerf-360 dataset, particularly in the background areas.
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/50fa0c7c-8585-45d2-ac4e-dea60e5b17aa">

I train the model using default settings with 4x downsampling images.

Have you experienced the same issue on your side, or could this be a mistake on my side?

**Comment by SuLvXiangXin** [comment]
Hi, I implement this repo mainly intended for object leval reconstruction, as it can be integrated into the inverse rendering pipeline. However, for unbounded scenes, I think the unsatisfactory results mainly due to the inadequet densification, especially in distant area. Maybe the densification process need some improvement. And you can also try to decrease the `densify_grad_threshold` and enlarge the `batch_size`.

**Comment by hyzhou404** [comment]
Thanks a lot.
